# Generated by Django 3.2.15 on 2022-12-22 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_alter_message_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(max_length=5)),
                ('messageid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='room.message')),
            ],
        ),
    ]
